# Generated by Django 5.1.5 on 2025-08-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0002_remove_order_food_item_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_by',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
