# Generated by Django 5.1.5 on 2025-08-28 10:00

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0003_order_ordered_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantOrder',
        ),
        migrations.AddField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='smartapp.order', verbose_name='Related Order'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='confidence',
            field=models.DecimalField(default=0.0, max_digits=5, decimal_places=2, verbose_name='Confidence Score'),
        ),
    ]
