# Generated by Django 5.1.5 on 2025-10-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0004_feedback_order_confidence'),
    ]

    operations = [
    ]
