# Generated by Django 5.1.5 on 2025-10-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0006_remove_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_wait_time',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
