# Generated by Django 5.1.5 on 2025-10-17 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0007_order_estimated_wait_time_order_ordered_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('voucher_code', models.CharField(max_length=20, unique=True)),
                ('discount_percentage', models.IntegerField(default=10)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='smartapp.feedback')),
            ],
            options={
                'verbose_name': 'Discount Voucher',
                'verbose_name_plural': 'Discount Vouchers',
            },
        ),
    ]
