# Generated by Django 5.1 on 2025-12-23 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0008_discountvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='emotion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='smartapp.order'),
        ),
    ]
