# Generated by Django 5.1 on 2025-12-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0010_admin_allergyinfo_kds'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
