# Generated by Django 5.1 on 2025-12-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0011_fooditem_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
